### ISSUE TITLE
[BUG] <i turn on my webcam and start signing but nothing gets translated and i cannot upload files>

### ISSUE THREAD

**Issue by nickysav91** [sign/translate#100]
### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
For future issues, please fill in the issue template. I'm closing this because it does not adhere to the template.

At the moment, there are no sign-language to spoken-language translation models implemented in the app.
The recent focus was on spoken-to-signed.

The next step for this to work is implementing this https://github.com/sign/translate/issues/72
