### ISSUE TITLE
Pose section (right side ) goes to infinite loop when enter few words 

### ISSUE THREAD

**Issue by NoureenKhawaja** [sign/translate#110]
### Current Behavior

when user enter word " merciful" or "lord" 
click enter button then

Pose section goes to infinite loop

![image](https://github.com/sign/translate/assets/146812315/ad55511c-953c-4cd0-8d65-740973d32230)

### Expected Behavior

application should display a "Pose" or if system does not get the word  or not available in DB then should display a message like"
Pose is not available" 

suggestion: i know numerous amount of word are available
So if "Merciful" not available then system should shows a Synonym 

### Steps To Reproduce

![image](https://github.com/sign/translate/assets/146812315/0b532e13-b868-4466-869d-664a0bc21ca1)

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
To be more exact, the bug is on the side of the pose -
The first time you enter something missing, it shows this:
<img width="1011" alt="image" src="https://github.com/sign/translate/assets/5757359/db9bc17f-92bd-4b72-844f-fd4cdc421913">

But then consequent errors don't show.
This is a bug in https://github.com/sign-language-processing/pose, but I'll keep it open here until I get to fix it

**Comment by AmitMY** [comment]
Fixed in https://github.com/sign-language-processing/pose/commit/71f5bd8fa8a0a35bd1461206555498d4c90cb9d5 and https://github.com/sign/translate/commit/4e7aa9891a52433d902bdd205f45268d7beb7715
