### ISSUE TITLE
Question/long term goal: automatic integration in YouTube videos

### ISSUE THREAD

**Issue by vpicouet** [sign/translate#112]
### Description

Hello,
Very interesting/impressive work with amazing potential!!!
How long do you think it could take to potentially have the possibility to have your sign language videos generated automatically (by Google, for example) and integrated directly into YouTube videos (on which subtitles are already generated automatically)?
5/10/20+ years? 
Is it something you already had in mind and have been discussing (with YouTube/Vimeo or other platforms)?
What do you see as the main challenges for getting there?
- computing power
- human resources / $ investment 
- integration / technology not developed yet on video platforms
I just checked [here](https://shkspr.mobi/blog/2019/05/adding-sign-language-to-html5-video/) that it is easy to overlay 2 videos using CSS. With the possibility to download the translations, you are already not far from allowing this (would be even better with transparent background though).
Thanks for your work!

**Comment by AmitMY** [comment]
We worked on something similar - an addon to YouTube to overlay the video:
https://www.youtube.com/watch?v=U9cIoQGm1cw

The problem is not the integration, but the translation quality. I believe that, given investment money and human resources (developers, researchers) it will take a few months to worst-case scenario two years until the system is usable and generates good, viable translations. It is a problem both of research and of lack of data.
