### ISSUE TITLE
[Question] Will sign.mt remain up?

### ISSUE THREAD

**Issue by JawadZ02** [sign/translate#126]
### Problem

Hi Amit, I plan on using the sign.mt website for my personal university app project to make sign language more accessible to deaf students. In one part of the app, I plan on simply displaying the website using a webview component for easy access. Now my question is, do you plan on keeping the sign.mt website up in the long term? I just want to be sure that the website won't go down in the following months. Please let me know. Thanks a lot.

**Comment by JawadZ02** [comment]
Surprisingly, I started facing an issue with the website today. As I was supplying some simple phrases in my testing to view their sign language animation, I started getting the message "connection already closed" on the pose viewer display. What is the cause of this issue?
Note: I even tried accessing the website from incognito and I still get the same message. So I am unable to use the website :(

**Comment by AmitMY** [comment]
That error sounds like internet issues.
The models are hosted on Google Cloud so I doubt the issue is with the server.
But please give me more details if you think that is the case.

This is what I am seeing:
![image](https://github.com/sign/translate/assets/5757359/3936ff13-ff3b-4003-86ed-5f0e20cd1e9d)
