### ISSUE TITLE
[BUG] What's the way to authenticate oneself for a local instance?

### ISSUE THREAD

**Issue by ashvaibhav** [sign/translate#165]
### Current Behavior

When following [instructions](https://github.com/sign/translate/blob/master/README.md) and running locally, the application runs but during translation (English --> ASL), I see error in browser stating `Parsing this body version is not implemented - 0.20000000298023224`.

Digging deeper into the network I see that all the calls made to firebaseappcheck are returning with 403 Error:
```
{
  "error": {
    "code": 403,
    "message": "App attestation failed.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.DebugInfo",
        "detail": "[ORIGINAL ERROR] generic::permission_denied: com.google.firebase.appcheck.providers.debug.DebugVerificationFailedException: App attestation artifact verification failed for app \"1:665830225099:web:18e0669d5847a4b047974e\". [google.rpc.error_details_ext] { message: \"App attestation failed.\" }"
      }
    ]
  }
}
```

Further, I see that the API key is checked in [here](https://github.com/sign/translate/blob/master/src/environments/environment.ts).

**Ask:** Could we add instructions to creating and registring firebaseappcheck API key?
Or am I doing something wrong?

### Steps To Reproduce

1. Run the application
2. Visit browser and http://localhost:4200/
3. Select languages English and American Sign Language.
4. Put some text in the English section.

Expect, ASL to show up

### Expected Behavior

Application to simply run with ASL showing up.

### Environment

- Browser: Chrome

**Comment by AmitMY** [comment]
> Parsing this body version is not implemented - 0.20000000298023224. 

does not source from the authentication issue, but from an outdated `pose-format` version. please make sure you pull the latest changes and install dependencies again (`npm install`)

It should then show, since there is no app attestation for the text to pose step, as far as i remember.
nevertheless, if you are experiencing an issue, it would print in console "your debug token is"
I could register your debug token, if you explain your use case. Otherwise, you'll need to host your own instance of https://github.com/sign-language-processing/spoken-to-signed-translation
