### ISSUE TITLE
[BUG] “Will” translating as “Want”

### ISSUE THREAD

**Issue by LLGHanson** [sign/translate#181]
### Current Behavior

Typing “I will go” translates as “I want go” in skeleton interpreter.

### Expected Behavior

”will” is a different sign

### Steps To Reproduce

Typing “I will go” translates as “I want go” in skeleton interpreter.

### Example flow

```
paste your flow here
```

### Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

**Comment by AmitMY** [comment]
Thank you. At the moment, we use a dictionary based translation.
This means we don't know how to deal with context, and in this case, "will" is translated as "want" since it is a synonym ("the will of the people") and without understanding context, it doesn't do well.

Our context based solution translates a little better - 
![image](https://github.com/user-attachments/assets/791a2920-e3f0-48a0-a9b4-11771d451819)

(the signs for `I`, and `future` +-, but the go was translated wrong)

We hope in the future to be better at this, but we can't do context disambiguation at the moment.
