### ISSUE TITLE
Wouldn't Firebase rather make your app non-free?

### ISSUE THREAD

**Issue by AmitMY** [sign/translate#81]
Wouldn't Firebase rather make your app non-free (FOSS-wise, not price-wise)? Maybe [Supabase](https://supabase.com/) or [appwrite](https://github.com/appwrite/appwrite) would be a better choice. That said, is the app available anywhere already? I cannot find an APK here, nor do I see a link to [F-Droid](https://f-droid.org/) or any similar place.

_Originally posted by @IzzySoft in https://github.com/sign/translate/issues/51#issuecomment-1484210454_

**Comment by AmitMY** [comment]
@IzzySoft - Ideally, everything in the app should work entirely offline.

Currently, we use firebase for:
1. server-side model inference where we have to run python code
2. model storage

Ideally, we would shift away from `1` to offer full offline support. Furthermore, all of the server-side code is indeed open-sourced, so if someone were to just run the cloud functions code on whatever server, that would work.

Regarding `2`, the model storage, that is a bit trickier - I would be happy to extend this service - https://github.com/sign/translate/blob/master/src/app/core/services/assets/assets.service.ts
To support more model/large-assets hosting services, or host them anywhere.

Besides those, the app is completely open-sourced. We do not rely on firebase-specific services like firestore or the realtime-database.

**Comment by AmitMY** [comment]
Since everything is open-sourced, and modifications such as removing firebase can be done with ease (the dependency is mostly analytics), closing this issue.

**Comment by IzzySoft** [comment]
That still means your APK will have it included, right? And not every person is capable of forking/cloning, making the proper adjustments, compile and sign their own build. Just saying. Would the app still work with Firebase removed? Would changing it be as simple as to comment out the dependency/dependencies in `build.gradle`? So: wouldn't it be better if the app were FOSS in its entirety, instead of requiring modifications to become FOSS?

Just thoughts, no pressure. But I wouldn't forgive myself not even having tried :wink:
