### ISSUE TITLE
Can't be able to run the project

### ISSUE THREAD

**Issue by ShakeelKhalid1913** [sign/translate#98]
Getting this issue while `npm install`

![image](https://github.com/sign/translate/assets/93911372/279fc144-3db7-44cb-91ad-e8c204e2f15d)

**Comment by ShakeelKhalid1913** [comment]
Still same issue :(

**Comment by AmitMY** [comment]
Please remove the `node_modules` directory, and try `npm install` again

**Comment by ShakeelKhalid1913** [comment]
I tried. but still same problem. i even cloned the project again.

![image](https://github.com/sign/translate/assets/93911372/2c8fb9ef-bcd0-40a9-95d6-2ce3cc93b9e1)

**Comment by ShakeelKhalid1913** [comment]
these packages were installed and then caught an error

![image](https://github.com/sign/translate/assets/93911372/473a5636-2aec-4a82-ad51-0eb975a9e82c)

**Comment by AmitMY** [comment]
It still looks like something is cached, because this command:
<img width="483" alt="image" src="https://github.com/sign/translate/assets/5757359/631d4a03-b766-4790-b3a9-ad80614a135a">
Is no longer in the code.

Can you please:
1. remove `node_modules`
2. Run `npm cache clean --force` to clean the cache, for reinstalling
3. `npm install

**Comment by ShakeelKhalid1913** [comment]
Is there any another way? because im still getting this issue.

is not it still in package.json? (sign/translate repo)
![image](https://github.com/sign/translate/assets/93911372/9e05de38-d21a-4615-8307-1c2638d2d733)

(sign/i18n repo)
![image](https://github.com/sign/translate/assets/93911372/f764ade4-f88c-448e-804f-6d0650dee5c8)

**Comment by AmitMY** [comment]
If the error is the exact same, then it's a caching issue, because the error says it is running the following command:
<img width="534" alt="image" src="https://github.com/sign/translate/assets/5757359/2507e245-da60-4f39-9a63-59b98279b47a">
which fails because you are on windows.

Two options:
1. purge cache
2. run `npm install` inside a bash terminal (git bash OR ubuntu subsystem for windows)

**Comment by ShakeelKhalid1913** [comment]
2nd Option worked, Thanks

**Comment by nickysav91** [comment]
i ran on gitbash and it said "compiled sucessfully" but then nothing happened

**Comment by ShakeelKhalid1913** [comment]
> im now signing but nothing is coming out on the translation end

Can you show me the output?
